#!/usr/bin/env bash
#
# Run all dotfiles installers.
cd "$(dirname $0)"

# ---

case "$OSTYPE" in
  darwin*)
    # Install homebrew if not already installed
    if test ! $(which brew); then
      echo "* Installing Homebrew..."
      ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi

    # Install all packages in the Brewfile
    echo "* Installing all packages in Brewfile..."
    brew update
    brew bundle -v
    brew cleanup
    ;;
  "linux-gnu")
    echo "* Installing packages..."
    sh "Aptfile"
    echo ""
    ;;
  *)
    echo "Unknown OS ($OSTYPE), skipping package installation."
    ;;
esac

# ---

CONFIG_DIR="$(cd "$(dirname "$0")" && pwd -P)/configs"

run_installers() {
  # config/ modules with install.sh files
  local files=($CONFIG_DIR/*/install.sh)
  for file in "${files[@]}"; do
    echo "> Setting up $(basename $(dirname $file))..."
    sh -c "$file"
  done
}

echo "* Running module installers..."
run_installers

echo ""
echo "* All done!"
