#!/usr/bin/env bash
#
# Run all dotfiles installers.
set -e
cd "$(dirname $0)"

# ---

case "$OSTYPE" in
  darwin*)
    # Install homebrew if not already installed
    if test ! $(which brew); then
      echo "* Installing Homebrew..."
      ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi

    # Install all packages in the Brewfile
    echo "* Installing all packages in Brewfile..."
    brew update
    brew bundle -v
    brew cleanup
    ;;
  "linux-gnu")
    echo "* Installing packages..."
    sh "Aptfile"
    echo ""
    ;;
  *)
    echo "Unknown OS ($OSTYPE), skipping package installation."
    ;;
esac

# ---

CONFIG_DIR="$(cd "$(dirname "$0")" && pwd -P)/configs"

run_installers() {
  local modules=  # list of modules to run installers from; order matters
  case "$OSTYPE" in
    darwin*)
      modules='ruby'
      ;;
    "linux-gnu")
      modules='ruby'
      ;;
    *)
      echo "! Unsupported OS ($OSTYPE); skipping module installation."
      ;;
  esac

  for module in ${modules}; do
    echo "  - $module/install.sh"
    sh -c "$CONFIG_DIR/$module/install.sh"
  done
}

echo "* Running module installers..."
run_installers

echo ""
echo "* All done!"
