#!/usr/bin/env bash
set -e

# CLI basics
sudo apt update && sudo apt install -y \
  zsh \
  vim \
  git \
  fzf \
  xsel \
  curl \
  imagemagick \
  ffmpeg \
  htop \
  autoconf \
  libssl-dev \
  ca-certificates \
  gnupg \
  lsb-release

# Add extra repos for docker & sublime
# docker: https://docs.docker.com/engine/install/ubuntu/
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg --yes
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# sublime-text: https://www.sublimetext.com/docs/linux_repositories.html#apt
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/sublimehq-archive.gpg > /dev/null
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list

# Refresh apt with new repos
sudo apt update && sudo apt install -y \
  docker-ce \
  docker-ce-cli \
  containerd.io \
  docker-compose-plugin \
  sublime-text
