#!/bin/sh
set -e

# Get sudo just to run the apt installs
sudo echo > /dev/null

# Configure extra repos
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
sudo add-apt-repository ppa:webupd8team/java
sudo add-apt-repository ppa:webupd8team/sublime-text-3
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BBEBDCB318AD50EC6865090613B00F1FD2C19886
sudo echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list

# Fundamentals
apt install zsh
apt install vim
apt install git
apt install imagemagick
apt install ffmpeg
apt install htop
apt install autoconf
apt install libssl-dev

# Ruby
apt install rbenv
apt install ruby-build

# Python
apt install python-dev
apt install python-pip
apt install python-setuptools

# Go
apt install golang

# Java
apt install oracle-java8-installer
apt install oracle-java9-installer
apt install gradle

# Apps
apt install sublime-text-installer
apt install spotify-client
apt install google-chrome-stable
