#!/usr/bin/env bash
# Wouldn't it be nice if cygwin had something like a Brewfile?

# Set up apt-cyg script
wget rawgit.com/transcode-open/apt-cyg/master/apt-cyg
install apt-cyg /bin
rm -rf apt-cyg

apt-cyg install zsh
apt-cyg install vim
