#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"

# ---

# Install homebrew if not already installed
if test ! $(which brew)
then
  echo "* Installing Homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# ---

# Install all packages in the Brewfile
echo "* Installing all packages in Brewfile..."
brew update
brew bundle -v
brew cleanup
brew cask cleanup

# ---

run_installers () {
  local config_dir="$(pwd -P)/configs"

  # Some installers need to run first (e.g. ruby, to install a rbenv ruby)
  local prioritized=('ruby')

  for installer in ${prioritized}; do
    echo "  - $p/install.sh"
    sh -c "$config_dir/$installer/install.sh"
  done

  # Find the rest of the installers and run them iteratively; order doesn't matter.
  local installers=$(ls configs/**/install.sh | grep -v -F $prioritized)

  # load the path files
  for installer in ${installers}; do
    conf="$(basename $(dirname ${installer}))"
    name=$(basename $(dirname ${installer}))/$(basename ${installer})
    echo "  - $name"
    sh -c "${installer}"
  done
}

echo "* Running all installers..."
run_installers

echo ""
echo "* All done!"
