# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[aws]
  symbol = "  "
  format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[buf]
  symbol = " "

[bun]
  symbol = " "

[c]
  symbol = " "
  format = '\[[$symbol($version(-$name))]($style)\]'

[cpp]
  symbol = " "
  format = '\[[$symbol($version(-$name))]($style)\]'

[cmake]
  symbol = " "
  format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
  format = '\[[⏱ $duration]($style)\]'

[dart]
  symbol = " "
  format = '\[[$symbol($version)]($style)\]'

[directory]
  read_only = " 󰌾"

[docker_context]
  symbol = " "
  format = '\[[$symbol$context]($style)\]'

[git_branch]
  symbol = " "
  format = '\[[$symbol$branch]($style)\]'

[git_status]
  format = '([\[$all_status$ahead_behind\]]($style))'

[git_commit]
  tag_symbol = '  '

[golang]
  symbol = " "
  format = '\[[$symbol($version)]($style)\]'

[gradle]
  symbol = " "
  format = '\[[$symbol($version)]($style)\]'

[hostname]
  ssh_symbol = " "

[java]
  symbol = " "
  format = '\[[$symbol($version)]($style)\]'

[kotlin]
  symbol = " "
  format = '\[[$symbol($version)]($style)\]'

[kubernetes]
  format = '\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
  symbol = " "
  format = '\[[$symbol($version)]($style)\]'

[memory_usage]
  symbol = "󰍛 "
  format = '\[$symbol[$ram( | $swap)]($style)\]'

[meson]
  symbol = "󰔷 "

[nim]
  symbol = "󰆥 "

[nix_shell]
  symbol = " "
  format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
  symbol = " "
  format = '\[[$symbol($version)]($style)\]'

[os]
  format = '\[[$symbol]($style)\]'

  [os.symbols]
    Alpaquita = " "
    Alpine = " "
    AlmaLinux = " "
    Amazon = " "
    Android = " "
    Arch = " "
    Artix = " "
    CachyOS = " "
    CentOS = " "
    Debian = " "
    DragonFly = " "
    Emscripten = " "
    EndeavourOS = " "
    Fedora = " "
    FreeBSD = " "
    Garuda = "󰛓 "
    Gentoo = " "
    HardenedBSD = "󰞌 "
    Illumos = "󰈸 "
    Kali = " "
    Linux = " "
    Mabox = " "
    Macos = " "
    Manjaro = " "
    Mariner = " "
    MidnightBSD = " "
    Mint = " "
    NetBSD = " "
    NixOS = " "
    Nobara = " "
    OpenBSD = "󰈺 "
    openSUSE = " "
    OracleLinux = "󰌷 "
    Pop = " "
    Raspbian = " "
    Redhat = " "
    RedHatEnterprise = " "
    RockyLinux = " "
    Redox = "󰀘 "
    Solus = "󰠳 "
    SUSE = " "
    Ubuntu = " "
    Unknown = " "
    Void = " "
    Windows = "󰍲 "

[package]
  symbol = "󰏗 "
  format = '\[[$symbol$version]($style)\]'

[perl]
  symbol = " "

[php]
  symbol = " "

[pijul_channel]
  symbol = " "

[pixi]
  symbol = "󰏗 "

[python]
  symbol = " "
  format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[ruby]
  symbol = " "
  format = '\[[$symbol($version)]($style)\]'

[rust]
  symbol = "󱘗 "
  format = '\[[$symbol($version)]($style)\]'

[scala]
  symbol = " "
  format = '\[[$symbol($version)]($style)\]'

[swift]
  symbol = " "
  format = '\[[$symbol($version)]($style)\]'

[sudo]
  format = '\[[as $symbol]($style)\]'

[terraform]
  format = '\[[$symbol$workspace]($style)\]'

[time]
  format = '\[[$time]($style)\]'

[username]
  format = '\[[$user]($style)\]'
